require: rubocop-rspec

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ClassLength:
  Max: 135

RSpec/ExampleLength:
  Max: 12

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Exclude:
    - "lib/active_support_ext/**/*.rb"
