require: rubocop-rspec

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
    Max: 20

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ClassLength:
  Max: 140

RSpec/ExampleLength:
  Max: 12

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 4

RSpec/NestedGroups:
  Max: 6

Style/Documentation:
  Exclude:
    - "lib/active_support_ext/**/*.rb"

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
