require: rubocop-rspec

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ClassLength:
  Max: 135

RSpec/ExampleLength:
  Max: 12

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Exclude:
    - "lib/active_support_ext/**/*.rb"

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
